export const transactionDirections = ["income", "expense", "transfer"] as const;
export const transactionSources = ["manual", "gmail"] as const;
export const transactionStatuses = ["completed", "pending", "flagged"] as const;

export const transactionCategories = [
  "food",
  "rent",
  "utilities",
  "transport",
  "shopping",
  "healthcare",
  "travel",
  "salary",
  "freelance",
  "transfers",
  "savings",
  "subscriptions",
  "education",
  "entertainment",
  "uncategorized",
] as const;

export const supportedBanks = [
  "BDO",
  "BPI",
  "UnionBank",
  "Metrobank",
  "Security Bank",
  "Landbank",
  "PNB",
  "EastWest Bank",
  "RCBC",
  "Chinabank",
  "PSBank",
  "AUB",
  "GCash",
  "Maya",
  "ShopeePay",
  "Coins.ph",
  "Tonik",
  "GoTyme",
  "SeaBank",
  "OwnBank",
  "CIMB",
  "ING Philippines",
  "Wise",
  "Payoneer",
  "Revolut",
] as const;

export const transactionCategoryKeywords: Record<string, string[]> = {
  food: ["restaurant", "cafe", "coffee", "food", "grabfood", "grocer", "landers", "sm supermarket"],
  rent: ["rent", "condo", "lease"],
  utilities: ["meralco", "maynilad", "internet", "pldt", "globe", "water", "electric"],
  transport: ["grab", "uber", "lrt", "mrt", "shell", "petron", "gas"],
  shopping: ["mall", "shopee", "lazada", "retail", "ayala", "department store"],
  healthcare: ["hospital", "clinic", "pharmacy", "watsons", "mercury drug"],
  travel: ["air", "cebu pacific", "philippine airlines", "hotel", "booking"],
  salary: ["salary", "payroll", "compensation"],
  freelance: ["client", "retainer", "invoice", "upwork", "payoneer"],
  transfers: ["transfer", "instapay", "pesonet", "wallet top-up"],
  savings: ["time deposit", "savings", "investment"],
  subscriptions: ["netflix", "spotify", "subscription", "adobe", "apple.com/bill"],
  education: ["tuition", "course", "udemy", "coursera"],
  entertainment: ["cinema", "movie", "steam", "playstation"],
  uncategorized: [],
};

export const transactionCategoryColors: Record<string, string> = {
  food: "#38BDF8",
  rent: "#4ADE80",
  utilities: "#FBBF24",
  transport: "#F87171",
  shopping: "#1A3045",
  healthcare: "#8CA0B8",
  travel: "#38BDF8",
  salary: "#4ADE80",
  freelance: "#38BDF8",
  transfers: "#8CA0B8",
  savings: "#4ADE80",
  subscriptions: "#FBBF24",
  education: "#38BDF8",
  entertainment: "#F87171",
  uncategorized: "#1A3045",
};
