export const TRANSACTION_FIELDS_FRAGMENT = `
  fragment TransactionFields on Transaction {
    id
    source
    sourceId
    type
    direction
    amount
    signedAmount
    currencyCode
    bankName
    bankInitials
    accountId
    accountName
    fromAccountId
    fromAccountName
    toAccountId
    toAccountName
    originalTransactionId
    merchantName
    merchant
    description
    category
    categoryLabel
    referenceNumber
    notes
    status
    kindLabel
    transactionDate
    happenedAt
    createdAt
    updatedAt
    gmailMessageId
    gmailThreadId
  }
`;
